/*
 * This source file was generated by the Gradle 'init' task
 */
package innossh.proto.example.struct;

public class StructExample {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new StructExample().getGreeting());
    }
}
